daemon/nodes.go

Needed for Sdkd tests. Could make it an option, if desired, but didn't think it necessary.

Add Net Admin capability to docker containers

---

packerfiles/aws-amzn2.pkr.hcl
service/ec2/ec2service.go

Use gp3 storage to reduce costs
Give snapshots a name to make them easier to identify in the ui
Add the ec2-user to the couchbase group so it can access logs/config files
Deploy x86 instances using the correct instance type

EC2 AMI changes

---

daemon/restserver.go
service/docker/dockerservice.go
service/ec2/ec2service.go
service/service.go

This can happen if the call to KillCluster fails for some reason. Work around this by storing the cluster id before allocating. Any clusters that couldn't be destroyed will get cleaned up after their timeout using the regular cleanup method.

SDKQE-2517: AWS instances not destroyed sometimes

---

daemon/json.go
daemon/restserver.go
helper/helper.go
service/cloud/cloudservice.go
service/common/clusters.go
service/common/encryption.go
service/common/node.go
service/docker/dockerservice.go
service/ec2/ec2service.go
service/options.go
service/service.go
store/metadatastore.go

This endpoint enables node to node encryption. You can pass a level (control or strict)
When strict mode is enabled we store a use secure flag in the cluster metadata so we know to use https for any rest API calls. We skip tls verification because we don't really care about testing this in cbdynclusterd itself.

SDKQE-2526: Add new endpoint /setup-cluster-encryption

---

service/common/encryption.go
service/common/node.go

When enabling auto failover again you must supply a timeout. Set it to the value from before it was disabled

SDKQE-2526: Correctly reset auto failover setting before enabling n2n encryption

---

daemon/restserver.go

You won't be able to connect if you don't pass the option so set it to true

Always use hostnames when setting up ec2 clusters.

---

packerfiles/aws-yum.pkr.hcl

Older server versions do not allow someone in the couchbase group to write there which is needed for cert auth

Allow couchbase group to write to /opt/couchbase/var/lib/couchbase

---

daemon/daemon.go
daemon/restserver.go
service/docker/dockerservice.go
service/service.go

Keep track of clusters we have allocated to limit it to a configurable max number.
Adds a new parameter docker-max-containers.
Before allocating we check the number of active containers + the number in the process of being allocated to prevent overprovisioning. If we can't allocate the required number we return a custom error. The outer logic then checks for this error and retries until we get a different error or the allocation succeeds. We also update the timeout for the cluster every time we retry so e.g. if it takes 30 minutes to allocate we add 30 minutes to the original timeout

SDKQE-2593: Limit number of containers

---

helper/helper.go
service/common/node.go

With 256mb, fts runs out of memory and heavily throttles itself causing test failures

SDKQE-2592: Set default fts memory quota to 512mb

---

service/common/manager.go
service/common/node.go

The minimum was recently increased to 1GB but this can be changed with an internal settings call

SDKQE-2615: Set lower min magma mem quota to allow existing tests to pass

---

service/cloud/cloudservice.go

- Kill cluster if add ip or user fails
- Retry add ip if AV-35851 occurs

Capella fixes

---

daemon/json.go
daemon/restserver.go
service/cloud/client.go
service/cloud/cloudservice.go
service/cloud/json.go
service/cloud/options.go
store/metadatastore.go

Builds on top of https://github.com/couchbaselabs/cbdynclusterd/pull/71
* Create cloud requests can supply an environment containing all the details needed to create cluster. If one is not supplied the defaults provided by the server side config file are used
* Support GCP clusters
* Support providing custom region, provider and singleAZ
Note: Clusters with custom environments will not show up in the ps command and will not be auto deleted

SDKQE-2676: Support per cluster environment settings

---

daemon/restserver.go
go.mod
go.sum
service/cloud/cloudservice.go
service/cloud/constants.go
service/cloud/json.go
service/cloud/options.go
store/metadatastore.go

This change allows Capella clusters to be created with custom images. For a successful deployment, an override token, server version and image must be supplied. The public API does not allow this functionality so deployment now uses the internal API.
Also, retry on bucket create failure because of AV-35851 which I've seen a few times

SDKQE-2683: Support custom server image for capella

---

packerfiles/aws-yum.pkr.hcl
service/common/install.go
service/common/nodes.go
service/ec2/ec2service.go
service/ec2/packer.go

Instead of downloading the build from within the packer ec2 instance, download it on the local machine (which is on the vpn) to /tmp and copy it over

SDKQE-2724: Download builds using vpn when building AMIs

---

daemon/json.go
daemon/restserver.go
dockerfiles/couchbase/centos7/Dockerfile
packerfiles/aws-yum.pkr.hcl
service/common/nodes.go
service/docker/dockerservice.go
service/docker/images.go
service/ec2/packer.go
service/service.go

Validated by creating a bucket, defaults to 64 vbuckets
{"name":"default","nodeLocator":"vbucket","bucketType":"membase","storageBackend":"couchstore","uuid":"85b69d02fd0b5fa0649689faf48a1814","uri":"/pools/default/buckets/default?bucket_uuid=85b69d02fd0b5fa0649689faf48a1814","streamingUri":"/pools/default/bucketsStreaming/default?bucket_uuid=85b69d02fd0b5fa0649689faf48a1814","numVBuckets":64,"bucketCapabilitiesVer":"","bucketCapabilities":["collections","durableWrite","tombstonedUserXAttrs","couchapi","subdoc.ReplaceBodyWithXattr","subdoc.DocumentMacroSupport","subdoc.ReviveDocument","preserveExpiry","rangeScan","dcp","cbhello","touch","cccp","xdcrCheckpointing","nodesExt","xattr"],"collectionsManifestUid":"1","ddocs":{"uri":"/pools/default/buckets/default/ddocs"},"vBucketServerMap":{"has …

SDKQE-2730: Support creating cluster in serverless mode

---

cluster/bucket.go
daemon/json.go
daemon/restserver.go
service/common/clusters.go
service/common/node.go
service/options.go

Verified by creating bucket with num-vbuckets 16 and width 1
```
[
{
"name": "default2",
"nodeLocator": "vbucket",
"bucketType": "membase",
"storageBackend": "couchstore",
"uuid": "51b14f1d29c74ba1272f1f291419031d",
"uri": "/pools/default/buckets/default2?bucket_uuid=51b14f1d29c74ba1272f1f291419031d",
"streamingUri": "/pools/default/bucketsStreaming/default2?bucket_uuid=51b14f1d29c74ba1272f1f291419031d",
"numVBuckets": 16,
"bucketCapabilitiesVer": "",
"bucketCapabilities": [
"collections",
"durableWrite",
"tombstonedUserXAttrs",
"couchapi",
"subdoc.ReplaceBodyWithXattr",
"subdoc.DocumentMacroSupport",
"subdoc.ReviveDocument",
"preserveExpiry",
"rangeScan",
"dcp",
"cbhello",
"touch",
"cccp",
"xdcrCheckpointing",
"nodesExt",
"xattr"
],
"collectionsManifestUid": "1",
"ddocs": { "uri": …
```

SDKQE-2731: Support width and vbucket count for serverless buckets

---

helper/helper.go
service/cloud/cloudservice.go
service/common/clusters.go
service/common/encryption.go
service/common/manager.go
service/common/node.go

Tested this on 6.6.5, 7.1.1 and 7.2.0-1831 serverless where this was previously timing out

SDKQE-2748: Load sample bucket should only check item counts in the default collection

---

README.md
cluster/node.go
daemon/daemon.go
daemon/json.go
daemon/restserver.go
service/common/certauth.go
service/common/clusters.go
service/common/node.go
service/common/nodes.go
service/ec2/ec2service.go

This PR is split into 2 commits. The first creates custom hostnames for ec2 nodes. This is required because we need to get a signed cert for a domain we own which we can't do for the default AWS hostnames. The second actually sets up the cluster with the certs that are provided in the config. I updated the README to document how to generate these certs because they will need to be regenerated every year after they expire.
The end result

SDKQE-2766: Automate platform cert testing

---

service/ec2/packer.go

they changed the name with the latest update. A better fix would be to use product code but that would require a separate packer file for amzn2 because amzn2 amis don't have a product id

SDKQE-2790: fix centos ami name

---

service/cloud/client.go
service/cloud/cloudservice.go
service/cloud/constants.go
service/cloud/json.go

SDKQE-3565 replace capella v3 api's to v4 api's
Use Capella v4 apis wherever v3 apis are being used.
```
// public API
deleteClusterPath  = "/v3/clusters/"
getClusterPath     = "/v3/clusters/"
getAllClustersPath = "/v3/clusters"
// TODO: Use public API when AV-27634 fixed
// createUserPath     = "/v3/clusters/%s/users"
clustersHealthPath = "/v3/clusters/%s/health"
```
cluster health endpoint is only used to get bucket's health which function is not being used anywhere in cbdynclusterd, so we can either remove it if this is no longer needed or find a way to get the bucket's health using v4 api's.

SDKQE-3565 replace capella v3 api's to v4 api's
